%% ------------- DEFINITION OF THE INPUTS/OUTPUT PATHS --------------------

%--------------- ISR baselines L2 -----------------------------------------
common_path='C:\Users\eduard.makhoul/isardSAT/projects/Sentinel-6/data/QR2/results/L2/MAT/INPUT_MAT/'
           
scenarios_path = strcat(common_path,{'02_S6A_OS2_2mSWH/S6A_OS21_0003_lat-40/LR_RMC_from_RAW/'});         
                                   
%subfolder defintion
baselines_subfolder={'adapted_RMC_onboard/data/','fixed_RMC_onboard/data/','fixed_mean_RMC_onboard/data/','adapted_marco_earth_RMC_onboard/data/',...
    'fixed_center_track_marco_earth_RMC_onboard/data/','fixed_marco_matrix_bis_RMC_onboard/data/','fixed_RMC_4_5_onboard/data/'};
baseline_name={'Adaptive RMC matrix','Fixed (Original-Thales-round error) RMC matrix','Fixed (Mean value- round error) RMC matrix','Adaptive (Marco radius) RMC matrix','Fixed center track (Marco radius) RMC matrix',...
    'Fixed (Mean value -round fixed) RMC matrix bis','Fixed RMC 4dot5 TAS'};           


ref_SSH=[12];
ref_SWH=[2];
ref_sigma0=[12];

% ref_SSH=[12];
% ref_SWH=[2];
% ref_sigma0=[12];

num_scenarios=length(scenarios_path);
num_baselines_comparison=length(baselines_subfolder);


%matrix cell array: columns are different baselines to be compared &
%horizontal different folders
input_path_L2_ISR_bs=cell(num_scenarios,num_baselines_comparison);
name_bs=cell(num_scenarios,num_baselines_comparison);

path_comparison_results=cell(num_scenarios,1);

for i_scenario=1:num_scenarios
    for i_baseline=1:num_baselines_comparison
        input_path_L2_ISR_bs(i_scenario,i_baseline)=...
            cellstr(strcat(scenarios_path{i_scenario},baselines_subfolder{i_baseline}));
        name_bs(i_scenario,i_baseline)=baseline_name(i_baseline);
    end
    %------------------ Path to save results -------------------------------
    path_comparison_results(i_scenario,1)=...
        cellstr(strcat(scenarios_path{i_scenario},'performance/'));
end


%----------------- ISRs L1Bs ----------------------------------------------
input_path_L1_ISR_bs=cell(num_scenarios,num_baselines_comparison);
input_path_L1_ISR_bs(:)={''};


%---------------------- ESA reference path for L2 data --------------------
input_path_L2_ESA=cell(num_scenarios,1);
input_path_L2_ESA(:)={''};
input_path_L1_ESA=cell(num_scenarios,1);
input_path_L1_ESA(:)={''};

%---------------- Starlab -------------------------------------------------
input_path_L2_STL=cell(num_scenarios,1);
input_path_L2_STL(:)={''};

%------------------ GPOD --------------------------------------------------
input_path_L2_GPOD=cell(num_scenarios,1);
input_path_L2_GPOD(:)={''};

% ----------------- KML files ---------------------------------------------
filename_mask_KML=cell(num_scenarios,1);
filename_mask_KML(:)={''};

%% ----------- DEFINITION OF THE OPTIONS ----------------------------------
mission='S6';

num_pools=1;
num_threads=1;

figure_format='jpg';
res_fig='-r300';

win_size_detrending=20;
step_SWH=0.10;
sh_name_nc='ssh';
define_min_max_SWH=1;
min_SWH=0.5;
max_SWH=10;

flag_outliers_removal=0;
type_outliers_removal='hampel';
smooth_param=1;
plot_downsampling=25;
generate_plots=1;
generate_plot_SSH=1;
generate_plot_SWH=1;
generate_plot_sigma0=1;
generate_plot_nb=1;
generate_plot_COR=1;
generate_plot_misspointing=0;
generate_kml=0;
filter_land_surf_type=0;
compute_comparison_performance_tracks=0;
filter_ISR_baselines_mask=0;

set_default_plot_ASR;

%% -------------------- INCLUSION OF SEARCH CODE PATH ---------------------
%NEED TO CHANGE IT TO YOUR LOCAL PATH
code_folder_full_path='C:/Users/eduard.makhoul/isardSAT/projects/SCOOP/processing/L2_GPP/Matlab_Code/';%'/home/emak/feina/projects/SCOOP/processing/L2_GPP/';%

cd(code_folder_full_path);
FolderInfo=dir(code_folder_full_path);
FolderInfo = FolderInfo(~cellfun('isempty', {FolderInfo.date})); 
aux=struct2cell(FolderInfo); %into a cell array where first row is 
folders=(aux(1,[FolderInfo.isdir]))'; %name is the first row
clear aux;
folders=strcat(code_folder_full_path,folders(~strcmp(folders,['.'])&~strcmp(folders,['..'])&~strcmp(folders,['.svn'])&~strcmp(folders,['inputs'])&~strcmp(folders,['old'])));
for i_folder=1:length(folders)
    addpath(genpath(char(folders(i_folder))));
end


version_matlab=version;

if num_threads > 1
	%open pools
	if str2double(version_matlab(end-5:end-2))>2013
        parpool(num_threads);
    else
        matlabpool('open',num_threads);
    end    
	
    parfor i_proc=1:num_scenarios
        call_performance_global(input_path_L2_ISR_bs,name_bs,path_comparison_results,i_proc,...
                                'figure_format',figure_format,...
                                'res_fig',res_fig,...
                                'win_size_detrending',win_size_detrending,...
                                'step_SWH',step_SWH,...
                                'sh_name_nc',sh_name_nc,...
                                'flag_outliers_removal',flag_outliers_removal,...
                                'type_outliers_removal',type_outliers_removal,...
                                'smooth_param',smooth_param,...
                                'input_path_L2_ESA',input_path_L2_ESA,...
                                'input_path_L1_ISR_bs',input_path_L1_ISR_bs,...
                                'input_path_L1_ESA',input_path_L1_ESA,...
                                'input_path_L2_STL',input_path_L2_STL,...
                                'input_path_L2_GPOD',input_path_L2_GPOD,...
                                'filename_mask_KML',filename_mask_KML,...
								'num_pools',num_pools,...
                                'generate_plots',generate_plots,...
                                'plot_downsampling',plot_downsampling,...
                                'define_min_max_SWH',define_min_max_SWH,...
                                'min_SWH',min_SWH,...
                                'max_SWH',max_SWH,...
                                'generate_kml',generate_kml,...
                                'filter_land_surf_type',filter_land_surf_type,...
                                'compute_comparison_performance_tracks',compute_comparison_performance_tracks,...
                                'generate_plot_SSH',generate_plot_SSH,'generate_plot_SWH',generate_plot_SWH,...
                                'generate_plot_sigma0',generate_plot_sigma0,'generate_plot_nb',generate_plot_nb,...
                                'generate_plot_COR',generate_plot_COR,...
                                'generate_plot_misspointing',generate_plot_misspointing,...
                                'filter_ISR_baselines_mask',filter_ISR_baselines_mask,...
                                'mission',mission,...
                                'ref_SSH',ref_SSH,...
                                'ref_SWH',ref_SWH,...
                                'ref_sigma0',ref_sigma0);
    end
    
	%close pools
    if str2double(version_matlab(end-5:end-2))>2013
        poolobj = gcp('nocreate');
        delete(poolobj);
    else
        matlabpool('close');
    end
else
    for i_proc=1:num_scenarios
        call_performance_global(input_path_L2_ISR_bs,name_bs,path_comparison_results,i_proc,...
                                'figure_format',figure_format,...
                                'res_fig',res_fig,...
                                'win_size_detrending',win_size_detrending,...
                                'step_SWH',step_SWH,...
                                'sh_name_nc',sh_name_nc,...
                                'flag_outliers_removal',flag_outliers_removal,...
                                'type_outliers_removal',type_outliers_removal,...
                                'smooth_param',smooth_param,...
                                'input_path_L2_ESA',input_path_L2_ESA,...
                                'input_path_L1_ISR_bs',input_path_L1_ISR_bs,...
                                'input_path_L1_ESA',input_path_L1_ESA,...
                                'input_path_L2_STL',input_path_L2_STL,...
                                'input_path_L2_GPOD',input_path_L2_GPOD,...
                                'filename_mask_KML',filename_mask_KML,...
								'num_pools',num_pools,...
                                'generate_plots',generate_plots,...
                                'plot_downsampling',plot_downsampling,...
                                'define_min_max_SWH',define_min_max_SWH,...
                                'min_SWH',min_SWH,...
                                'max_SWH',max_SWH,...
                                'generate_kml',generate_kml,...
                                'filter_land_surf_type',filter_land_surf_type,...
                                'compute_comparison_performance_tracks',compute_comparison_performance_tracks,...
                                'generate_plot_SSH',generate_plot_SSH,'generate_plot_SWH',generate_plot_SWH,...
                                'generate_plot_sigma0',generate_plot_sigma0,'generate_plot_nb',generate_plot_nb,...
                                'generate_plot_COR',generate_plot_COR,...
                                'generate_plot_misspointing',generate_plot_misspointing,...
                                'filter_ISR_baselines_mask',filter_ISR_baselines_mask,...
                                'mission',mission,...
                                'ref_SSH',ref_SSH,...
                                'ref_SWH',ref_SWH,...
                                'ref_sigma0',ref_sigma0);
    end
end

                           