function []=call_L2_processing_parallel(input_path_L1B,output_path_L2,cnf_chd_cst_path,...
                                proc_bsln_id,filter_input_file,num_pools,filename_mask_KML,...
                                PTR_along_external,PTR_across_external,i_proc)

if isempty(PTR_along_external) && isempty(PTR_across_external)
   PTR_along_value =[];
   PTR_across_value =[];
elseif isempty(PTR_along_external) && ~isempty(PTR_across_external)
   PTR_along_value =[];
   PTR_across_value =PTR_across_external(i_proc);        
elseif ~isempty(PTR_along_external) && isempty(PTR_across_external)
   PTR_along_value =PTR_along_external(i_proc);
   PTR_across_value =[];
else
   PTR_along_value =PTR_along_external(i_proc);
   PTR_across_value =PTR_across_external(i_proc); 
end

L2_bulk_processing_paralelization(char(input_path_L1B(i_proc)),...
    char(output_path_L2(i_proc)),...
    char(cnf_chd_cst_path(i_proc)),...
    'num_pools',num_pools(i_proc),...
    'filename_mask_KML',char(filename_mask_KML(i_proc)),...
    'proc_bsln_id',char(proc_bsln_id(i_proc)),...
    'filter_input_file',char(filter_input_file(i_proc)),...
    'PTR_along_external',PTR_along_value,...
    'PTR_across_external',PTR_across_value);
                            
end